language: python

python:
  - 3.6

env:
  - DJANGO=2.0.2

before_install:
  - export DJANGO_SETTINGS_MODULE=playlist.settings
  - export PYTHONPATH=$HOME/builds/inoks/m3u8
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install -r flake8
  - pip install django==$DJANGO --quiet

before_script:
  - flake8

script:
  - python ./manage.py test